######################################################################
# Automatically generated by qmake (2.01a) Wed Dec 11 10:25:08 2024
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += main.cpp
